server:
  port: 7070

spring:
  application:
    name: CRICKETTEAMS-SERVICE
    
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost